spring:
  application:
    name: digital-wallet

  data:
    mongodb:
      uri: mongodb://admin:password@localhost:27017/digitalwallet?authSource=admin
      database: digitalwallet

server:
  port: 8080

logging:
  level:
    com.wallet: DEBUG