services:
  mongodb:
    image: mongo:7
    container_name: wallet-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: digitalwallet
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7.2-alpine
    container_name: wallet-redis
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data

volumes:
  mongo-data:
  redis-data:
